services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file: .env
    environment:
      PYTHONPATH: /app
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    command: ["celery", "-A", "app.celery_app.celery", "worker", "-l", "info"]
    env_file: .env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  beat:
    build: .
    command: ["celery", "-A", "app.celery_app.celery", "beat", "-l", "info"]
    env_file: .env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  flower:
    build: .
    command: ["celery", "--broker=${CELERY_BROKER_URL}", "flower", "--port=5555", "--address=0.0.0.0"]
    env_file: .env
    environment:
      PYTHONPATH: /app
    ports:
      - "5555:5555"
    depends_on:
      api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  pgdata: {}
